version: '3.0'

x-spark-common: &spark-common
  # build:
  #   context: .
  #   dockerfile: Dockerfile.Spark
  image: bitnami/spark:3.5
  environment:
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
  volumes:
    - ./shared:/mnt/shared
  networks:
    - bigdata-net

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.Airflow
  env_file:
    - airflow.env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./jobs:/opt/airflow/jobs
    - ./shared:/mnt/shared
  depends_on:
    - postgres
  networks:
    - bigdata-net

services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - airflow-db-data:/var/lib/postgresql/data
    networks:
      - bigdata-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - bigdata-net

  # mysql:
  #   image: mysql:9
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql


  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_MASTER_URL: spark://spark-master:7077
    deploy:
      replicas: 1

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_MASTER_URL: spark://spark-master:7077
    deploy:
      replicas: 1

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: bash -c "airflow db migrate && airflow users create --username airflow --firstname Long --lastname Nguyen --role Admin --email long.nguyen@ecotruck.vn --password airflow && airflow scheduler"
    # command: bash -c "airflow scheduler"

networks:
    bigdata-net:

volumes:
    minio_data:
    airflow-db-data: